;;; -*- lexical-binding: t; no-byte-compile: t -*-
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; This file is the part of "Plum" project under the BSD-2-Clause License.    ;
;;; Copyright (C) 2026 Komeil Parseh <komeilparseh@disroot.org> & Contributors.;
;;;                                                                            ;
;;; WARNING: This file is *automatically* generated by tangling an org file.   ;
;;; DO NOT EDIT THIS FILE DIRECTLY. All changes must be made in the source file;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-module (plum parser)
  #:export (parse))
